apiVersion: apps/v1
kind: Deployment
metadata:
  name: ndc14-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ndc14-backend
  template:
    metadata:
      labels:
        app: ndc14-backend
    spec:
      containers:
      - name: backend
        image: yourdockerhub/ndc14-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: database-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: jwt-secret
---
apiVersion: v1
kind: Service
metadata:
  name: ndc14-backend-service
spec:
  selector:
    app: ndc14-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
