apiVersion: apps/v1
kind: Deployment
metadata:
  name: ndc14-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ndc14-frontend
  template:
    metadata:
      labels:
        app: ndc14-frontend
    spec:
      containers:
      - name: frontend
        image: yourdockerhub/ndc14-frontend:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ndc14-frontend-service
spec:
  selector:
    app: ndc14-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
