apiVersion: apps/v1
kind: Deployment
metadata:
  name: ndc14-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ndc14-db
  template:
    metadata:
      labels:
        app: ndc14-db
    spec:
      containers:
      - name: postgresql
        image: postgres:latest
        env:
        - name: POSTGRES_USER
          value: your_postgres_user
        - name: POSTGRES_PASSWORD
          value: your_postgres_password
        - name: POSTGRES_DB
          value: ndc14
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: ndc14-db-service
spec:
  selector:
    app: ndc14-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
