# .github/workflows/ingress.yml
name: Ingress Deployment

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Kubernetes CLI
        uses: azure/setup-kubectl@v2
        with:
          version: 'v1.22.0'  # Specify your kubectl version here

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend Docker Image
        run: |
          docker build -t mmycin/ndc14-backend:latest ./backend
          docker push mmycin/ndc14-backend:latest

      - name: Build and Push Frontend Docker Image
        run: |
          docker build -t mmycin/ndc14-frontend:latest ./frontend
          docker push mmycin/ndc14-frontend:latest

      - name: Apply Kubernetes Ingress and Deployments
        run: |
          kubectl apply -f kubernetes/backend-deployment.yaml
          kubectl apply -f kubernetes/frontend-deployment.yaml
          kubectl apply -f kubernetes/postgres-deployment.yaml
          kubectl apply -f kubernetes/db-secret.yaml
          kubectl apply -f kubernetes/jwt-secret.yaml
          kubectl apply -f kubernetes/ingress.yaml

      - name: Verify Deployment Status
        run: |
          kubectl rollout status deployment/ndc14-backend
          kubectl rollout status deployment/ndc14-frontend

      - name: Ping-Checker Job
        run: |
          curl -f http://your-ingress-url.com || exit 1
